#!/usr/bin/bash
set -euxo pipefail

git init --bare $HOME/.dotfiles
alias ,cfg='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
,cfg config status.showUntrackedFiles no

,cfg remote add origin https://github.com/tpwo/dotfiles.git
,cfg fetch

# Rename files, so Git can perform checkout. This could be smarter e.g. using
# 'ls' and 'git ls-files' and doing it for each conflicting file :)
mv .bashrc .bashrc.bak

,cfg checkout wsl
,cfg status
