default_session = "Users/tpwo"
bookmarks = [
    "/Users/tpwo",
    "/Users/tpwo/.config/nvim",
    "/Users/tpwo/.ssh",
    "/Users/tpwo/notes",
    "/Users/tpwo/ws/sandbox",
]

[[search_dirs]]
path = "/Users/tpwo/ws/private/repos/tpwo"
depth = 1

[[search_dirs]]
path = "/Users/tpwo/ws/sandbox"
depth = 1
