" Check for vim-tiny which lacks 'eval'
if has("eval")
  let skip_defaults_vim=1
endif

set nocompatible

syntax enable

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set encoding=utf-8 " Be explicit when $LANG is wrong

set complete+=kspell " Suggest dict words when 'spell' is enabled
set dictionary+=/usr/share/dict/words " Use common dictionary
set spelllang=en,pl
set spellfile=$HOME/.vim/spell/spellfile.utf-8.add

set expandtab      " Insert spaces when pressing a tab
set tabstop=4      " Set how many columns are used to render a tab
set shiftwidth=0   " Reuse tabstop value
set softtabstop=-1 " Reuse shiftwidth value

" Disable automatic folding
set foldmethod=manual
set nofoldenable

set number
set cursorline

set scrolloff=10

" Configure statusline
" Based on:
" https://shapeshed.com/vim-statuslines/
" https://learnvimscriptthehardway.stevelosh.com/chapters/17.html
set statusline=
set statusline+=%.40f              " Relative path to the file
set statusline+=%m                 " Modified [+] flag, [-] when unmodifiable
set statusline+=%r                 " Read only [RO] flag
set statusline+=%=                 " Align to right
set statusline+=\ %y               " File type
set statusline+=\ %{&fileencoding?&fileencoding:&encoding} " UTF-8 etc.
set statusline+=\[%{&fileformat}\] " Unix/DOS line endings
set statusline+=\ %4l:%-2c         " Line and column number with padding
set statusline+=\ %3p              " % of file at cursor with padding
set statusline+=%%                 " Verbatim '%' sign

" Always display the status line
set laststatus=2

" Highlight search hits
set hlsearch

" Highlight as you search
set incsearch

set ignorecase
set smartcase

set formatoptions+=1 " Don't break a line after a one-letter word

" Enable mouse (sic!) for very convenient resizing of splits
set mouse=a

" Without it resizing split doesn't work in Windows Terminal
set ttymouse=sgr

function! EnsureDir(path)
  let dir = expand(a:path)

  if !isdirectory(dir)
    call mkdir(dir, 'p')
  endif

  return dir
endfunction

let backup_dir = EnsureDir('~/.vim/backup')
let swap_dir   = EnsureDir('~/.vim/swap')
let undo_dir   = EnsureDir('~/.vim/undo')

" Create temp files at $HOME/.vim instead of near edited file.
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

" Edit/Reload vimrc configuration file
command ConfigEdit :e $MYVIMRC
command ConfigReload :source $MYVIMRC

" Leave the default Leader key as \, but alias Space to it. I found an
" opinion that this prevents some kinds of timeout or delay issues.
map <SPACE> <Leader>

" With space as leader, when pressed two times, just act as space
nnoremap <silent> <Leader><Space> <Space>

" Disable search highlighting
nnoremap <silent> <Leader>l :nohlsearch<CR>

" Make Y consistent with C and D
nnoremap Y y$

" Enable omni-completion
set omnifunc=syntaxcomplete#Complete

" Force some file names to be specific file type
autocmd bufnewfile,bufRead *.bash*       set ft=bash
autocmd bufnewfile,bufRead *.profile     set filetype=sh
autocmd bufnewfile,bufRead *.crontab     set filetype=crontab
autocmd bufnewfile,bufRead *ssh/config   set filetype=sshconfig
autocmd bufnewfile,bufRead .dockerignore set filetype=gitignore
autocmd bufnewfile,bufRead *gitconfig    set filetype=gitconfig
autocmd bufnewfile,bufRead justfile      set filetype=make

" Set options based on filetype
autocmd FileType yaml      setlocal tabstop=2
autocmd FileType sh        setlocal tabstop=2
autocmd FileType bash      setlocal tabstop=2
autocmd FileType vim       setlocal tabstop=2
autocmd FileType sass      setlocal tabstop=4 shiftwidth=4
autocmd FileType markdown  setlocal spell linebreak smartindent
autocmd FileType asciidoc  setlocal spell linebreak smartindent
autocmd FileType gitcommit setlocal spell
autocmd FileType gitconfig setlocal noexpandtab

" Avoid unintentional switches to Ex mode
nnoremap Q <nop>

" Avoid unintentional sending Vim to background
nnoremap <C-z> <nop>

" Store relative line number jumps in the jumplist if they exceed
" a threshold.
nnoremap <expr> k (v:count > 5 ? "m'" . v:count : '') . 'k'
nnoremap <expr> j (v:count > 5 ? "m'" . v:count : '') . 'j'

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^Eterm'
  set t_Co=16
endif

" Disable beep and flash
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

if $THEME == 'dark'
  set background=dark
  colorscheme habamax
else
  set background=light
  colorscheme shine
endif
